module ApplicationHelper
  SALARY_LEVEL_MIN = %w(10000_dollars 20000_dollars 30000_dollars 40000_dollars 50000_dollars 60000_dollars 70000_dollars 80000_dollars 90000_dollars)
  EDUCATION_LEVEL = %w(less_than_a_high_school_diploma high_school_diploma post_secondary_certificate some_college_courses associates_degree bachelors_degree post_baccalaureate_certificate masters_degree post_masters_certificate first_professional_degree doctoral_degree post_doctoral_training)
  EDUCATION_TYPES = %w(degree_program continuing_education_course online_education certification)
  SORT_OPTIONS = %w(national_salary best_match)
end
